# Generated by Django 3.2.5 on 2022-07-20 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20220720_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='shops.menu')),
                ('service_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shops', to='shops.servicesite')),
            ],
        ),
    ]
