# Generated by Django 3.2.5 on 2022-07-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_contracttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conract_type', to='shops.contracttype')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shop_id', to='shops.shop')),
            ],
        ),
    ]
