# Generated by Django 3.2.5 on 2022-08-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
