# Generated by Django 3.2.5 on 2022-08-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_auto_20220807_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesite',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicesite',
            name='radius',
            field=models.IntegerField(default=10),
        ),
    ]
