# Generated by Django 3.2.5 on 2022-08-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_auto_20220818_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpslocation',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gpslocation',
            name='long',
            field=models.FloatField(default=0.0),
        ),
    ]
