# Generated by Django 3.2.5 on 2022-08-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_auto_20220819_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpslocation',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpslocation',
            name='long',
            field=models.FloatField(),
        ),
    ]
