# Generated by Django 3.2.5 on 2022-08-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_auto_20220819_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GpsLocation',
        ),
        migrations.AddField(
            model_name='servicesite',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='servicesite',
            name='long',
            field=models.FloatField(null=True),
        ),
    ]
