# Generated by Django 3.2.5 on 2022-08-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_auto_20220827_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='weigh',
            new_name='weight',
        ),
    ]
