# Generated by Django 3.2.5 on 2022-08-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_rename_weigh_menuitem_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
