# Generated by Django 3.2.5 on 2022-08-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0018_auto_20220828_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
