# Generated by Django 3.2.5 on 2022-08-31 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderdetails_item'),
        ('shops', '0020_alter_menuitemprice_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItemPrice',
        ),
    ]
