# Generated by Django 4.1 on 2022-09-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drone",
            name="drone_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="drone_type",
                to="drones.dronetype",
            ),
        ),
    ]
