# Generated by Django 3.2.5 on 2022-07-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_shoptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ServiceSites',
            new_name='ServiceSite',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
