# Generated by Django 3.2.5 on 2022-08-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_auto_20220807_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='service_site',
        ),
    ]
