# Generated by Django 3.2.5 on 2022-08-07 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_auto_20220807_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='shops.menu'),
        ),
        migrations.AddField(
            model_name='shop',
            name='service_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Shops', to='shops.servicesite'),
        ),
    ]
