# Generated by Django 3.2.5 on 2022-08-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0019_alter_menuitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemprice',
            name='price',
            field=models.FloatField(),
        ),
    ]
