# Generated by Django 3.2.5 on 2022-08-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0002_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appusers.group'),
            preserve_default=False,
        ),
    ]
