# Generated by Django 3.2.5 on 2022-07-20 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('self_weigh', models.IntegerField()),
                ('payload_weigh', models.IntegerField()),
                ('external_reference', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('drone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone_type', to='drones.dronetype')),
            ],
        ),
    ]
