# Generated by Django 4.1 on 2022-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drone",
            name="description",
            field=models.CharField(max_length=50),
        ),
    ]
