# Generated by Django 4.1 on 2022-09-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0002_alter_drone_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dronetype", old_name="payload_weigh", new_name="payload_weight",
        ),
        migrations.RenameField(
            model_name="dronetype", old_name="self_weigh", new_name="self_weight",
        ),
        migrations.AlterField(
            model_name="dronetype",
            name="description",
            field=models.CharField(max_length=50),
        ),
    ]
