# Generated by Django 4.1 on 2022-09-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0003_rename_payload_weigh_dronetype_payload_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dronetype",
            name="external_reference",
            field=models.CharField(max_length=25),
        ),
    ]
