# Generated by Django 4.1 on 2022-09-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0004_alter_dronetype_external_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dronetype",
            name="external_reference",
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
