# Generated by Django 3.2.5 on 2022-08-31 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='item',
        ),
    ]
