# Generated by Django 4.1 on 2022-09-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_items"),
    ]

    operations = [
        migrations.DeleteModel(name="OrderRow",),
        migrations.AddField(
            model_name="order", name="total_weight", field=models.FloatField(default=0),
        ),
    ]
