# Generated by Django 4.1 on 2022-09-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0022_menuitem_price"),
        ("orders", "0008_orderrow_rename_total_order_total_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(to="shops.menuitem"),
        ),
    ]
